package com.marketfinder.di

import com.marketfinder.core.data.local.AppDatabase
import com.marketfinder.core.di.coreModule
import com.marketfinder.core.di.platformModule
import org.koin.core.module.Module
import org.koin.core.module.dsl.singleOf
import org.koin.core.module.dsl.factoryOf
import org.koin.core.module.dsl.viewModelOf
import org.koin.core.module.dsl.bind
import org.koin.dsl.module

fun moduleList(): List<Module> = listOf(
    platformModule(),
    coreModule(),
    appModule()
)

fun appModule() = module {
    // Project-specific DI registrations (generated by code gen)
}
